# https://github.com/adrienverge/yamllint
# config https://yamllint.readthedocs.io/en/stable/configuration.html
# rule https://yamllint.readthedocs.io/en/stable/rules.html
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

# For all rules
ignore: |
  vendor/

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning


