# https://github.com/marketplace/actions/license-eye
# config file

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: weizhoublue
    # optional, regex match license header
    pattern: |
      Copyright|Apache-2.0
    # for fix pr
    content: |
      Copyright 2022 Authors of weizhoublue
      SPDX-License-Identifier: Apache-2.0

  paths:
    - '**/*.go'
    - '**/*.sh'

  paths-ignore:
    - 'vendor'
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'go.mod'
    - 'go.sum'
    - 'LICENSE'
    - 'NOTICE'

  comment: on-failure
