header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: weizhoublue

    content: |
      Copyright 2022 Authors of weizhoublue
      SPDX-License-Identifier: Apache-2.0

    pattern: |
      Copyright|Apache-2.0

  paths: # <6>
    - '**/*.go'
    - '**/*.sh'

  paths-ignore:
    - 'vendor'
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'go.mod'
    - 'go.sum'
    - 'LICENSE'
    - 'NOTICE'

  comment: on-failure