codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 100%

comment:
  layout: "reach"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

  
