

# get VERSION
include  ../Makefile.defs


all: update-versions docs


#update version in chart
update-versions:
	$(ECHO_GEN) " -> Updating version to $(VERSION)"
	@# Update chart versions to point to the current version.