# build the Beta image with customized tag ,under an clean env , from  specified Branch
# build image like: ghcr.io/weizhoublue/github-action-test/controllerimage-{beta}:{yourTag}
name: Build Image Beta

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'tag, sha, branch'
        required: true
        default: v1.0.0

permissions: write-all

jobs:
  call-workflow:
    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
    uses: ./.github/workflows/call-release-image.yaml
    with:
      ref: ${{ github.event.inputs.ref }}
      suffix: 'beta'
