# cleaner for ghcr image , each day
# NOTE: at now only orgs is supported , for personal it fail
#This action uses the Github Rest API deletePackageVersionForOrg() resource which states:
#To use this endpoint, you must have admin permissions in the organization and authenticate using an access token with the packages:read and packages:delete scopes. In addition: [...] If package_type is container, you must also have admin permissions to the container you want to delete.
#  As a result, for this action to work, the token must be associated to a user who has admin permissions for both the organization and the package. If this is not the case, then dry-runs will work as expected but actual runs will fail with a Package not found error when attempting to delete versions.

name: Clean Image CI At Interval

env:
  ONLINE_REGISTER: ghcr.io

on:
  schedule:
    # Run the GC at 3am each day
    - cron: "0 3 * * *"

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: controllerimage
    steps:
      - name: Delete CI image
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ env.ONLINE_REGISTER }}/${{ github.repository }}/${{ matrix.name }}-ci
          dry-run: false # Dry-run first, then change to `false`
          # Minimum age in days of a version before it is pruned. Defaults to 0 which matches all versions of a container
          # longer than 1 days, will gc it
          older-than: 1 # days
          # Count of most recent, matching containers to exclude from pruning
          keep-last: 0
          #untagged versions should be pruned
          untagged: true
          # if no tag-regex , all tag will be pruned
          tag-regex: ${{ steps.tag.outputs.tag }}*