name: Auto Daily Build

on:
  schedule:
    # run 1:30 each day
    - cron: "30 1 * * *"
  workflow_dispatch:
    inputs:
      ref:
        description: 'sha, tag, branch'
        required: true
        default: main

jobs:

