name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  schedule:
    # Run the GC at 3am each day
    - cron: "0 3 * * *"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/micnncim/action-label-syncer
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          # delete all existing labels which is not mentioned in manifest
          prune: false