name: Label Approved PR

on: pull_request_review

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      # https://github.com/abinoda/label-when-approved-action
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@v1.0.7
        env:
          APPROVALS: "2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          #REMOVE_LABEL: "awaiting%20review"