name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:
  schedule:
    # run 4:00 am each day in shanghai timezone
    # cron by UTC, shanghai timezone = UTC + 8
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/micnncim/action-label-syncer
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          # delete all existing labels which is not mentioned in manifest
          prune: true
