name: Lint Licnese checks

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request: {}
  push:
    branches:
      - main

permissions: read-all

# for each pr, queue all workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Ref
        id: version
        shell: bash
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            tag_name=${{ github.event.inputs.ref }}
            echo ::set-output name=ref::${tag_name}
          else
            echo ::set-output name=ref::${{ github.sha }}
          fi

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ steps.version.outputs.ref }}

      # https://github.com/marketplace/actions/license-eye
      - name: Check License Header
        id: checklicense
        uses: apache/skywalking-eyes@main
        with:
          mode: fix

      - name: Apply Changes
        if: ${{ steps.checklicense.outputs.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
