name: Lint Label Check for release

# Trigger the workflow on pull requests only
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  RELEASE_LABELS: "release/bug, release/feature, release/docs, release/changelog, release/none-required"

jobs:
  check-label:
    name: Check release-note label set
    runs-on: ubuntu-latest
    steps:
      # must set one of required label, for release note generator
      - uses: mheap/github-action-required-labels@v1.2.0
        with:
          mode: exactly
          count: 1
          labels: ${{ env.RELEASE_LABELS }}

