name: Lint Licnese checks

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request:
    paths:
      - '**.go'
      - '**.sh'
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.sh'
  workflow_dispatch:
    inputs:
      ref:
        description: 'sha, ref, branch'
        required: true
        default: main

permissions: read-all

# for each pr, queue all workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Ref
        id: version
        shell: bash
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }}; then
            tag_name=${{ github.event.inputs.ref }}
            echo ::set-output name=ref::${tag_name}
          elif ${{ github.event_name == 'push' }} ; then
              echo ::set-output name=ref::${{ github.sha }}
          elif ${{ github.event_name == 'pull_request' }} || ${{ github.event_name == 'pull_request_target' }} ; then
              echo "trigger by pull_request_target"
              echo ::set-output name=tag::${{ github.event.pull_request.head.sha }}
          else
            echo ::set-output name=ref::${{ github.sha }}
          fi

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ steps.version.outputs.ref }}

      # https://github.com/marketplace/actions/license-eye
      # config file: .licenserc.yaml
      - name: Check License Header
        id: checklicense
        uses: apache/skywalking-eyes@main
        with:
          log: debug
          config: .licenserc.yaml
