# must enable github page in your project
# all charts under "charts/*", this workflow will create the tgz chart and merge to "/docs" of "chart" branch
# please make the "chart" branch as the github page
# please create the "chart" branch beforhand, or else the workflow will fail
# put all charts under /docs/charts/*.tgz, and /docs/index.yaml

name: Release Charts

env:
  HELM_VERSION: v3.8.1
  PR_LABEL: pr/release/robot_chart
  PR_REVIWER: weizhoublue

on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Base: tag, branch or sha . main branch as default'
        required: true
        default: main
      dest_branch:
        description: 'Dest_branch: the destination branch. chart branch as default'
        required: true
        default: chart

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - chart_dir: charts/cilium

    steps:
      - name: Get Version
        id: get_version
        continue-on-error: false
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }} ; then
              ver=${{ github.event.inputs.base }}
              echo ::set-output name=version::${ver}

              dest=${{ github.event.inputs.dest_branch }}
              echo ::set-output name=dest::${dest}
          else
              echo ::set-output name=version::main
              echo ::set-output name=dest::main
          fi

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_version.outputs.version }}

      - name: Get Base URL
        id: get_base_url
        run: |
          name=${{ github.repository }}
          proj=${name#*/}
          url=https://${{ github.repository_owner }}.github.io/${proj}
          echo "::set-output name=url::${url}"

      - name: Install Helm
        uses: azure/setup-helm@v2.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Prepare Chart
        continue-on-error: false
        run: |
          chart_dir=${{ matrix.chart_dir }}
          [ ! -d "${chart_dir}" ] && echo "error, fail to find directory ${chart_dir}" && exit 1
          mkdir _tmp
          cd _tmp
          helm package ../${chart_dir}
          cd ..
          mkdir -p docs/charts
          mv _tmp/*.tgz docs/charts
          rm -rf _tmp

      - name: Prepare Index
        continue-on-error: false
        run: |
          cd docs
          helm repo index  ./charts  --url ${{ steps.get_base_url.outputs.url }}/charts
          mv ./charts/index.yaml ./

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          title: "robot Update chart from ${{ steps.get_version.outputs.version }} to branch ${{ steps.get_version.outputs.dest }} "
          # from branch
          commit-message: "robot Update chart from ${{ steps.get_version.outputs.version }} to branch ${{ steps.get_version.outputs.dest }} "
          # branch name: ${branch}-${branch-suffix}
          # an branch suffix could make sure the branch is unique
          branch-suffix: timestamp
          branch: update_chart
          # Delete the branch when closing pull requests, and when undeleted after merging
          delete-branch: true
          # merge to
          base: ${{ steps.get_version.outputs.dest }}
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}
