name: Release Charts

env:
  HELM_VERSION: v3.8.1
  CHART_DIR: charts/cilium

on:
  workflow_call:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Project Name
        id: get_project
        run: |
          echo "::set-output name=project::${github.repository#*/}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v2.0
        with:
          version: ${{ env.HELM_VERSION }}

      # https://github.com/helm/chart-releaser-action
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          #  chart-releaser version
          # https://github.com/helm/chart-releaser
          version: v1.3.0
          charts_dir: ${{ env.CHART_DIR }}
          # where to publish the chart . use github page
          charts_repo_url: https://${{ github.repository_owner }}.github.io/${{ steps.get_project.outputs.project }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"