# must enable github page in your project
name: Release Charts

env:
  HELM_VERSION: v3.8.1
  MERGE_TO_BRANCH: main
  PR_LABEL: pr/release/robot_chart
  PR_REVIWER: weizhoublue

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag, if empty , use main branch'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - chart_dir: charts/cilium

    steps:
      - name: Get Version
        id: get_version
        continue-on-error: false
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }} ; then
              ver=${{ github.event.inputs.tag }}
              if [ -n "$ver" ] ; then
                echo ::set-output name=version::${ver}
                exit 0
              fi
          fi
          echo ::set-output name=version::main

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_version.outputs.version }}

      - name: Get Base URL
        id: get_base_url
        run: |
          name=${{ github.repository }}
          proj=${name#*/}
          url=https://${{ github.repository_owner }}.github.io/${{ steps.get_project.outputs.project }}
          echo "::set-output name=url::${url}"

      - name: Install Helm
        uses: azure/setup-helm@v2.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Prepare Chart
        continue-on-error: false
        run: |
          chart_dir=${{ matrix.chart_dir }}
          [ ! -d "${chart_dir}" ] && echo "error, fail to find directory ${chart_dir}" && exit 1
          mkdir _tmp
          cd mkdir
          helm package ../${chart_dir}
          cd ..
          mkdir -p docs/charts
          mv _tmp/*.tgz docs/charts
          rm -f _tmp

      - name: Prepare Index
        continue-on-error: false
        run: |
          cd docs
          helm repo index  ./charts  --url ${{ steps.get_base_url.outputs.url }}/charts

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          title: "robot Update chart from ${{ steps.get_version.outputs.version }} "
          # from branch
          commit-message: "robot Update chart from ${{ steps.get_version.outputs.version }}"
          # branch name: ${branch}-${branch-suffix}
          # an branch suffix could make sure the branch is unique
          branch-suffix: timestamp
          branch: update_chart
          # Delete the branch when closing pull requests, and when undeleted after merging
          delete-branch: true
          # merge to
          base: ${{ env.MERGE_TO_BRANCH }}
          signoff: true
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}
