# must enable github page in your project
# all charts under "charts/*", this workflow will create the tgz chart and merge to "/docs" of "chart" branch
# please make the "chart" branch as the github page
# please create the "chart" branch beforhand, or else the workflow will fail
# put all charts under /docs/charts/*.tgz, and /docs/index.yaml

name: Release Charts

env:
  HELM_VERSION: v3.8.1
  PR_LABEL: pr/release/robot_chart
  PR_REVIWER: weizhoublue
  MERGE_BRANCH: webserver

on:
  workflow_dispatch:
    inputs:
      base:
        description: 'Base: tag or sha'
        required: true
        default: v1.0.0

jobs:
  generate_chart:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - chart_dir: charts/cilium

    steps:
      - name: Get Version
        id: get_version
        continue-on-error: false
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }} ; then
              ver=${{ github.event.inputs.base }}
              echo ::set-output name=version::${ver}
          else
              echo ::set-output name=version::main
          fi

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_version.outputs.version }}

      - name: Get Base URL
        id: get_base_url
        run: |
          name=${{ github.repository }}
          proj=${name#*/}
          url=https://${{ github.repository_owner }}.github.io/${proj}
          echo "::set-output name=url::${url}"

      - name: Install Helm
        uses: azure/setup-helm@v2.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Prepare Chart
        continue-on-error: false
        run: |
          cd charts
          make clean
          make
          if ! ls *.tgz &>/dev/null ; then
            echo "failed to generate chart"
            exit 1
          fi
          cd ..
          mkdir -p tmp/charts
          mv charts/*.tgz tmp/charts
          git checkout -- charts
          # rebuild index.yaml
          cd tmp
          helm repo index  ./charts  --url ${{ steps.get_base_url.outputs.url }}/charts
          mv ./charts/index.yaml ./

      - name: Upload Chart Package
        uses: actions/upload-artifact@v3.0.0
        with:
          name: chart-package
          path: tmp/charts/*
          retention-days: 1
          if-no-files-found: error

      - name: Upload Chart Yaml
        uses: actions/upload-artifact@v3.0.0
        with:
          name: chart-package
          path: tmp/index.yaml
          retention-days: 1
          if-no-files-found: error

      # https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy To GithubPages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          # The target branch the action should deploy to.
          branch: github-pages
          # The folder of original branch should deploy.
          folder: tmp
          # target directory of target branch
          target-folder: '.'
