name: test workflow_call

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'tag, sha, branch'
        required: true
        default: v1.0.0

jobs:
  call-workflow:
    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
    uses: ./.github/workflows/release-chart.yaml
    with:
      ref: ${{ github.event.inputs.ref }}

  result:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }}
