name: test workflow_call

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'tag, sha, branch'
        required: true
        default: v1.0.0

jobs:
  call-workflow-context:
    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
    uses: ./.github/workflows/show-context.yaml
    with:
      myname: ${{ github.event.inputs.ref }}

  call-workflow-golang:
    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
    uses: ./.github/workflows/lint-golang.yaml
    with:
      sha: ${{ github.event.inputs.ref }}

#  #===============
#  call-workflow-chart:
#    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
#    uses: ./.github/workflows/call-release-chart.yaml
#    with:
#      ref: ${{ github.event.inputs.ref }}
#
#  handler-result-chart:
#    runs-on: ubuntu-latest
#    needs: call-workflow-chart
#    steps:
#      - name: Download Artifact
#        uses: actions/download-artifact@v3.0.0
#        with:
#          name: ${{ needs.call-workflow-chart.outputs.artifact }}
#          path: ./
#
#      - name: result
#        run: |
#          echo ${{ needs.call-workflow-chart.outputs.artifact }}
#          ls ./
#
#  #===============
#  call-workflow-changelog:
#    uses: ./.github/workflows/call-release-changelog.yaml
#    with:
#      dest_tag: ${{ github.event.inputs.ref }}
#
#  handler-result-changelog:
#    runs-on: ubuntu-latest
#    needs: call-workflow-changelog
#    steps:
#      - name: Download Artifact
#        uses: actions/download-artifact@v3.0.0
#        with:
#          name: ${{ needs.call-workflow-changelog.outputs.artifact }}
#          path: ./
#
#      - name: result
#        run: |
#          echo ${{ needs.call-workflow-changelog.outputs.artifact }}
#          ls ./

